POST http://localhost:6969/auth/register
Content-Type: application/json

{
	"email": "test999@mail.com",
	"password": "testtest",
	"name": "test999@mail.com",
	"avatar": "testtest"
}

--{%

local body = context.json_decode(context.result.body)

context.set_env("TOKEN", body.token)

--%}

###

POST http://localhost:6969/auth/login
Content-Type: application/json

{
	"email": "test999@mail.com",
	"password": "testtest"
}

--{%

local body = context.json_decode(context.result.body)

context.set_env("TOKEN", body.token)

--%}
